language: perl

perl:
  - "5.26"

env:
  - COVERAGE="codecov coveralls"

sudo: false

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto --always-upgrade-modules

install:
  - cpan-install --deps
  - cpan-install --coverage

before_script:
  - coverage-setup

script:
  - prove -lv $(test-dirs)

after_success:
  - coverage-report
