language: perl
perl:
  - "5.26"
sudo: false
before_install:
    - perlbrew install-cpanm -f
install:
    - (cpanm --installdeps --with-develop -nq .) || cat ~/.cpanm/build.log
script:
    - prove -lr t -j9
