language: perl

perl:
  - "5.26"

cache:
  directories:
    - ~/perl5

env:
  - COVERAGE=1

sudo: false

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto --always-upgrade-modules
  - local-lib

install:
  - cpan-install --deps
  - cpan-install --coverage

before_script:
  - coverage-setup

script:
  - prove -lv $(test-dirs)

after_success:
  - coverage-report
