language: perl

perl:
  - "5.26"

env:
  - COVERAGE=1

sudo: false

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - cpan-install --deps
  - cpan-install --coverage

before_script:
  - coverage-setup

script:
  - prove -lv $(test-dirs)

after_success:
  - coverage-report
