language: perl

perl:
  - "5.14"

install:
  - cpanm --quiet --installdeps --notest .

script:
  - perl Build.PL
  - ./Build build
  - cover -test -ignore_re '^t/|^local/'

after_success:
  - cover -report codecov
