language: perl
perl:
  - "5.26"
before_install:
    - cpanm Carton
install:
    - carton install
    - export PERL5LIB=$(pwd)/local/lib/perl5:$(pwd)/lib:$PERL5LIB
script:
    - carton exec -- prove -Ilib -lv t
